import { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "PaperCloud",
    done: 3,
    total: 10,
    percentDone: 30,
    color: "--solid-1",
  },
  {
    id: 2,
    title: "Polyma",
    done: 7,
    total: 10,
    percentDone: 70,
    color: "--solid-2",
  },
  {
    id: 3,
    title: "Obim",
    done: 5,
    total: 10,
    percentDone: 50,
    color: "--solid-3",
  },
  {
    id: 4,
    title: "fitbybunmi.com",
    done: 0,
    total: 10,
    percentDone: 0,
    color: "--solid-8",
  },
  {
    id: 5,
    title: "Examen",
    done: 9,
    total: 10,
    percentDone: 90,
    color: "--solid-5",
  },
  {
    id: 6,
    title: "Momos Tula",
    done: 2,
    total: 10,
    percentDone: 20,
    color: "--solid-6",
  },
  {
    id: 7,
    title: "Susan",
    done: 0,
    total: 10,
    percentDone: 0,
    color: "--solid-7",
  },
];
