import Head from "next/head";
import Status from "@/components/Status";
import Content from "@/components/Content";
import Projects from "@/components/Projects";
import { MenuToggle } from "@/components/MenuToggle";
import { motion, useCycle } from "framer-motion";

export default function Home() {
  const [isOpen, toggleOpen] = useCycle(false, true);

  return (
    <motion.div
      initial={{
        scale: 1.095,
        y: 30,
      }}
      animate={{
        scale: 1,
        y: 0,
      }}
      transition={{
        duration: 0.2,
        // delay: 0.1,
      }}
    >
      <Head>
        <title>Ace Progress Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <motion.div initial={false} animate={isOpen ? "open" : "closed"}>
          <MenuToggle toggle={() => toggleOpen()} />
        </motion.div>
        <Status />
        <Projects />
      </Content>
    </motion.div>
  );
}
