import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Status from "@/components/Status";
import Content from "@/components/Content";
import Card from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ace Progress Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <Status />
        <Card />
      </Content>
    </>
  );
}
